dist: trusty
sudo: false
cache:
  bundler: true
  directories:
  - cache/
notifications:
  email: false
language: c
compiler: gcc
env:
  global:
  - PACKAGE=cups
  - PACKAGE2=cups-bjnp
  - USER=arition
  - REPO=openwrt-cups
  - DEPLOYREPO=openwrt-repo
  matrix:
  - OSVER=LEDE_17.01      SDK_URL=https://downloads.lede-project.org/releases/17.01.4/targets/ipq806x/generic/lede-sdk-17.01.4-ipq806x_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64.tar.xz
  - OSVER=OpenWrt_15.05   SDK_URL=https://archive.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
  - OSVER=LEDE_17.01      SDK_URL=https://downloads.lede-project.org/releases/17.01.4/targets/ar71xx/nand/lede-sdk-17.01.4-ar71xx-nand_gcc-5.4.0_musl-1.1.16.Linux-x86_64.tar.xz
  - OSVER=OpenWrt_15.05   SDK_URL=https://archive.openwrt.org/chaos_calmer/15.05.1/ramips/mt7620/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
  - OSVER=LEDE_17.01      SDK_URL=https://downloads.lede-project.org/releases/17.01.4/targets/ramips/mt7620/lede-sdk-17.01.4-ramips-mt7620_gcc-5.4.0_musl-1.1.16.Linux-x86_64.tar.xz
  - OSVER=OpenWrt_15.05   SDK_URL=https://archive.openwrt.org/chaos_calmer/15.05.1/brcm63xx/generic/OpenWrt-SDK-15.05.1-brcm63xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
  - OSVER=LEDE_17.01      SDK_URL=https://downloads.lede-project.org/releases/17.01.4/targets/brcm63xx/generic/lede-sdk-17.01.4-brcm63xx-generic_gcc-5.4.0_musl-1.1.16.Linux-x86_64.tar.xz
  - OSVER=OpenWrt_15.05   SDK_URL=https://archive.openwrt.org/chaos_calmer/15.05.1/bcm53xx/generic/OpenWrt-SDK-15.05.1-bcm53xx_gcc-4.8-linaro_uClibc-0.9.33.2_eabi.Linux-x86_64.tar.bz2
  - OSVER=LEDE_17.01      SDK_URL=https://downloads.lede-project.org/releases/17.01.4/targets/bcm53xx/generic/lede-sdk-17.01.4-bcm53xx_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64.tar.xz
  - OSVER=OpenWrt_15.05   SDK_URL=https://archive.openwrt.org/chaos_calmer/15.05.1/brcm47xx/generic/OpenWrt-SDK-15.05.1-brcm47xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
  - OSVER=LEDE_17.01      SDK_URL=https://downloads.lede-project.org/releases/17.01.4/targets/brcm47xx/generic/lede-sdk-17.01.4-brcm47xx-generic_gcc-5.4.0_musl-1.1.16.Linux-x86_64.tar.xz
  - OSVER=OpenWrt_15.05   SDK_URL=https://archive.openwrt.org/chaos_calmer/15.05.1/mvebu/generic/OpenWrt-SDK-15.05.1-mvebu_gcc-4.8-linaro_uClibc-0.9.33.2_eabi.Linux-x86_64.tar.bz2
  - OSVER=LEDE_17.01      SDK_URL=https://downloads.lede-project.org/releases/17.01.4/targets/mvebu/generic/lede-sdk-17.01.4-mvebu_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64.tar.xz
  - OSVER=OpenWrt_15.05   SDK_URL=https://archive.openwrt.org/chaos_calmer/15.05.1/x86/generic/OpenWrt-SDK-15.05.1-x86-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
  - OSVER=LEDE_17.01      SDK_URL=https://downloads.lede-project.org/releases/17.01.4/targets/x86/generic/lede-sdk-17.01.4-x86-generic_gcc-5.4.0_musl-1.1.16.Linux-x86_64.tar.xz
  - OSVER=OpenWrt_15.05   SDK_URL=https://archive.openwrt.org/chaos_calmer/15.05.1/x86/64/OpenWrt-SDK-15.05.1-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
  - OSVER=LEDE_17.01      SDK_URL=https://downloads.lede-project.org/releases/17.01.4/targets/x86/64/lede-sdk-17.01.4-x86-64_gcc-5.4.0_musl-1.1.16.Linux-x86_64.tar.xz
  - OSVER=OpenWrt_15.05   SDK_URL=https://archive.openwrt.org/chaos_calmer/15.05.1/kirkwood/generic/OpenWrt-SDK-15.05.1-kirkwood_gcc-4.8-linaro_uClibc-0.9.33.2_eabi.Linux-x86_64.tar.bz2
  - OSVER=LEDE_17.01      SDK_URL=https://downloads.openwrt.org/releases/17.01.4/targets/kirkwood/generic/lede-sdk-17.01.4-kirkwood_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64.tar.xz
install:
- mkdir -p $TRAVIS_BUILD_DIR/local ; cd $TRAVIS_BUILD_DIR/local
- wget "http://archive.ubuntu.com/ubuntu/pool/main/c/ccache/ccache_3.3.4-1_amd64.deb"
- dpkg -x *.deb .
- mkdir -p $TRAVIS_BUILD_DIR/cache ; cd $TRAVIS_BUILD_DIR/cache
- wget -c $SDK_URL
- mkdir -p $TRAVIS_BUILD_DIR/sdk ; cd $TRAVIS_BUILD_DIR/sdk
- export FILE=$TRAVIS_BUILD_DIR/cache/$(basename $SDK_URL)
- file $FILE
- if [ "$OSVER" = "OpenWrt_15.05" ]; then tar xjf $FILE && SDK_DIR="OpenWrt-SDK-*"; elif [ "$OSVER" = "LEDE_17.01" ]; then tar Jxf $FILE && SDK_DIR="lede-sdk-*"; fi
- cd $TRAVIS_BUILD_DIR/sdk/$SDK_DIR
- mkdir package/$PACKAGE
- ln -s $TRAVIS_BUILD_DIR/$PACKAGE/Makefile package/$PACKAGE/
- ln -s $TRAVIS_BUILD_DIR/$PACKAGE/files package/$PACKAGE/
- ln -s $TRAVIS_BUILD_DIR/$PACKAGE/patches package/$PACKAGE/
- mkdir package/$PACKAGE2
- ln -s $TRAVIS_BUILD_DIR/$PACKAGE2/Makefile package/$PACKAGE2/
script:
- export PATH=$TRAVIS_BUILD_DIR/local/usr/bin:$PATH
- cd $TRAVIS_BUILD_DIR/sdk/$SDK_DIR
- export SDK_DIR=$(basename `pwd`)
- export PATH=$TRAVIS_BUILD_DIR/sdk/$SDK_DIR/staging_dir/host/bin:$PATH
- pushd staging_dir/toolchain-*
- TOOLCHAIN_DIR=$(basename `pwd`)
- export PATH=$TRAVIS_BUILD_DIR/sdk/$SDK_DIR/staging_dir/$TOOLCHAIN_DIR/bin:$PATH
- popd
- ./scripts/feeds update packages >/dev/null
- ./scripts/feeds update base >/dev/null
- ./scripts/feeds install libjpeg
- ./scripts/feeds install libpng
- ./scripts/feeds install zlib
- ./scripts/feeds install libusb-1.0
- make defconfig
- make package/$PACKAGE/compile V=s
- make package/$PACKAGE2/compile V=s
- find $TRAVIS_BUILD_DIR/sdk/$SDK_DIR/bin/
- find . -name *cups*.ipk -exec cp {} $TRAVIS_BUILD_DIR \;
- cd $TRAVIS_BUILD_DIR/
- chmod a+x $TRAVIS_BUILD_DIR/deploy.sh
after_success: "$TRAVIS_BUILD_DIR/deploy.sh"
before_install:
- echo $enc_key | gpg --passphrase-fd 0 secret.key.gpg
